### ISSUE TITLE
能不能得到每个函数的行号呢

### ISSUE THREAD

**Issue by sdrgroup** [magicsky/sya#8]
我试了你的方法，可以获得函数名称什么的，但是却无法得到行号，请问有什么办法得到每个函数的起始位置呢？
谢谢。

**Comment by magicsky** [comment]
可以的，我参考一下我另外一个项目: https://github.com/magicsky/DiffCoverage/blob/master/src/com/alibaba/qa/diffcoverage/parser/CoverageFileParser.java#L255

**Comment by magicsky** [comment]
我第一个研究eclipse的API也是为了拿到函数的起始位置
